spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/threatscope
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false  # Skip validation to let V10 run
  data:
    mongodb:
      uri: mongodb://admin:PASSWORD@localhost:27017/your_database_name?replicaSet=rs0&authSource=admin
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:PASSWORD}
  profiles:
    active: dev

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds


# Logging Configuration
# API Documentation - Common settings
springdoc:
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  use-root-path: false
  # These settings will be overridden by profile-specific configurations
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

# Enable Swagger UI in development
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

# Disable Swagger UI in production
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Disable Elasticsearch health check
management:
  health:
    elasticsearch:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.threatscopebackend: DEBUG

# Monitoring Configuration
monitoring:
  scheduler:
    enabled: true
    optimized: true
    # These will be overridden by database configurations
  real_time:
    interval: 300000  # 5 minutes
    max_checks: 100
    batch_size: 20
  hourly:
    interval: 3600000  # 1 hour
  daily:
    interval: 86400000  # 24 hours
  weekly:
    interval: 604800000  # 7 days
  max_concurrent_checks: 50
  batch_size: 10
  max_parallel_threads: 20

alerts:
  max_per_day: 1000
  cleanup_days: 90

notifications:
  batch_size: 100

cleanup:
  batch_size: 1000

system:
  health_check_interval: 600000  # 10 minutes
