# OAuth2 Client Configuration
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:}
            client-secret: ${FACEBOOK_CLIENT_SECRET:}
            scope:
              - email
              - public_profile
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}
            scope:
              - user:email
              - read:user

# Application OAuth2 Properties
app:
  oauth2:
    # Comma-separated list of authorized redirect URIs
    authorized-redirect-uris: "http://localhost:3000/oauth2/redirect,http://localhost:3000"
    # Default token expiration in milliseconds (1 hour)
    token-expiration-millis: 3600000
    # Default refresh token expiration in milliseconds (30 days)
    refresh-token-expiration-millis: 2592000000

# JWT Configuration
jwt:
  # Secret key for signing JWT tokens (use a secure random string in production)
  secret: ${JWT_SECRET:your-256-bit-secret}
  # Token expiration in milliseconds (1 hour)
  expiration-in-ms: 3600000
  # Refresh token expiration in milliseconds (30 days)
  refresh-expiration-in-ms: 2592000000

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "authorization,content-type,x-auth-token"
  exposed-headers: "x-auth-token"
  allow-credentials: true
